using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EFPlayground.DbModels;

//class that represents a videogame in the database
public class VideoGameDb
{
    //primary key for the video game in the database
    [Key]
    
    // set the primary key to be generated by the database
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    
    // set the primary key to be read-only
    [ReadOnly(true)]
    public int Id { get; set; }
    
    //the title of the video game
    public string? Title { get; set; }
    
    //the genre of the video game
    public string Genre { get; set; } = "";
    
    // the price of the video game
    public decimal Price { get; set; }
    
    // the release date of the video game
    public int ReleaseDate { get; set; }
    
    // a collection of reviews for this video game
    public ICollection<VideoGameReviewDb> VideoGameReviews { get; set; } 
}